googletest/src/matchers/matches_pattern.rs, googletest/tests/lib.rs, googletest/tests/matches_pattern_test.rs
The last release included a change which redirected matches_pattern! to matches_pattern_internal!. It did not fix the references inside the macros themselves to use $crate::matches_pattern_internal!. This worked fine in contexts where matches_pattern_internal! was already imported, but does not work in general client code where it is not. This change adds the $crate qualifier to each invocation of matches_pattern_internal!.
This also moves the tests of matches_pattern! out of the module and into a new integration test (see https://doc.rust-lang.org/rust-by-example/testing/integration_testing.html). This causes the tests to be compiled from outside the crate itself, precluding this type of bug in the future.
Fixes #86
=> Fix the matches_pattern! macro.

googletest/src/lib.rs
This reduces duplication in the description of the evaluation target of `verify_that!` and fixes the link behind `Result<()>`.
It also makes the links to `std::result::Result` explicit to avoid confusion with `googletest::Result`.
=> Fix the wording of the first few paragraphs of the crate documentation.

googletest/src/matchers/conjunction_matcher.rs
The existing example referenced a struct which is not visible to the reader, so it could not easily be copied out. Making the struct visible would create a great deal more visible clutter.
This PR changes the example to use strings and the `starts_with` and `ends_with` matchers. It also adds some failing examples for more illustration.
=> Improve the example in the documentation for the `and` extension method.

googletest/src/matchers/pointwise_matcher.rs
These examples clarify that the second argument may be a `Vec` and not just an array. They also show how one can use the matcher with other actual value types.
=> Add some more examples to the `pointwise!` documentation.

googletest/src/matchers/matches_pattern.rs, googletest/src/matchers/property_matcher.rs, googletest/tests/property_matcher_test.rs
This change:
* Moves the admonition about pure functions up to near the top of the documentation, and replaces "Note" with "Important".
* Adds the same admonition to the documentation of `matches_pattern!`.
* Adds an example showing that a method returning string slices cannot be used, and removes the blockquote around that part.
* Clarifies that only string slices are affected by the aforementioned limitation.
* Adds a test which verifies that array slices are indeed okay.
=> Reorganise the docs of the `property!` and `matches_pattern!` macros.

googletest/Cargo.toml, googletest/src/lib.rs, googletest/src/matcher_support/edit_distance.rs, googletest/src/matchers/eq_deref_of_matcher.rs, googletest/src/matchers/eq_matcher.rs, googletest/src/matchers/str_matcher.rs
The existing diff algorithm iterated over both the left and right lists in a nested loop, resulting in quadratic execution time. This resulted in noticeably long runtimes to produce diff input in realistic cases.
The new implementation uses the [algorithm of Myers](https://neil.fraser.name/writing/diff/myers.pdf) to achieve O((M+N)D) performance, where M and N are the input lengths and D is the maximum permitted [edit distance](https://en.wikipedia.org/wiki/Edit_distance). This is the same algorithm used in most existing tools and libraries and should offer acceptable performance. This implementation does not apply the enhancements suggested in the paper to reduce memory use and improve asymptotic complexity.
The maximum permitted edit distance is a constant in the `edit_distance` module. …
=> Rewrite the edit distance implementation using Myers algorithm

googletest/crate_docs.md, googletest/src/matchers/char_count_matcher.rs, googletest/src/matchers/mod.rs, googletest/src/matchers/str_matcher.rs
Previously, there was no matcher on just the length of a string. The existing matcher `len` only works on containers, not strings.
The concept of "length of a string" is itself slightly ambiguous -- it could mean byte length, character count, or number of grapheme clusters. This matcher unambiguously counts characters, which should be correct in most cases.
=> Introduce a matcher `char_count` to match string slices and owned strings with a particular character count.

.github/workflows/ci.yml, googletest/Cargo.toml, googletest/crate_docs.md, googletest/src/internal/test_outcome.rs, googletest/src/lib.rs, googletest/tests/proptest_integration_test.rs
Previously, it was awkward to use GoogleTest Rust assertions in Proptest property tests and to return GoogleTest `Result` from such tests. This required a fair amount of manual type conversion.
This adds two trait implementations behind an optional dependency on the `proptest` crate:
* An implementation of 'IntoTestResult` allows easily converting the output of `TestRunner` into a GoogleTest `Result`.
* An implementation of `From<TestAssertionFailure>` for `TestCaseError` allows easily using GoogleTest macros such as `verify_that!` inside `TestRunner::run`.
In particular, with this change, it is much easier to have property-based tests using `proptest` which do not panic on failure but rather communicate failures using `Result`, as is idiomatic in GoogleTest.
=> Add a shim to ease integration with the [proptest](https://crates.io/crates/proptest) crate.

googletest/src/matcher_support/edit_distance.rs, googletest/src/matcher_support/summarize_diff.rs, googletest/src/matchers/display_matcher.rs, googletest/src/matchers/eq_deref_of_matcher.rs, googletest/src/matchers/eq_matcher.rs, googletest/src/matchers/str_matcher.rs
This will produce the following result, which makes more obvious what colors and +/- means.
This triggered the following refactoring:
* Don't rely on `left` and `right` to describe the argument of `edit_list`. 
* Accept `actual` as first argument and `expected` as second (like in `verify_that!`)
* Use Red vs Green instead of Red vs Blue for better contrast.
* Use `-` for `actual` and `+` for `expected`. In a TTD process, expected is the ground truth that the code should generate, hence it reads as the recommendation: `The code should remove the `-` lines and generate the `+` lines.
=> Add an explanation header to the difference summary

googletest/src/internal/test_outcome.rs, googletest_macro/src/lib.rs, integration_tests/Cargo.toml, integration_tests/src/fatal_and_non_fatal_failure.rs, integration_tests/src/integration_tests.rs, run_integration_tests.sh
Previously the function generated by the `#[googletest]` macro would be `()`. This resulted in a Clippy warning that `()` did not implement `std::errror::Error`. It would also result in a slightly confusing test failure output:
```
...test assertion failure output...
Error: ()
```
The new empty struct `TestFailure` implements `std::error::Error` and displays to a more helpful message referring to the test assertion failure output above.
=> Introduce `TestFailure` to be `Result::Err` for the generated outer function of `#[googletest]` tests.

googletest/crate_docs.md, googletest/src/assertions.rs, googletest/src/lib.rs, googletest/src/matchers/tuple_matcher.rs, googletest/tests/composition_test.rs, googletest/tests/tuple_matcher_test.rs
This means that one can just put a bunch of matchers into a tuple and the result will itself be a matcher against corresponding tuples:
```
let value = (1, 2);
verify_that!(value, (eq(1), eq(2)))
```
There is no need for a separate macro for this, since one can implement `Matcher` for a tuple of matchers directly.
This is a breaking change, since it eliminates the `tuple!` macro. To port existing code, one just removes the call to `tuple!` and adds a trailing comma if necessary.
=> Replace the `tuple!` macro with an implementation of `Matcher` for tuples

googletest/Cargo.toml, googletest/src/matcher_support/summarize_diff.rs
Do not rely on a ANSI crate but just use the ANSI character hardcoded.
* ansi-term is not maintained anymore
* nu-ansi-term requires a Rust version higher than our current minimum version
* overall, we are not doing anything too fancy with colors.
* this may change in the future, which can lead to the need for a crate which would support our requirements.
=> Do not rely on a color term crate to generate ANSI character

googletest/src/internal/test_outcome.rs, googletest/src/lib.rs
This allows a test to check whether the current test has passed or failed based on non-fatal assertions such as `expect_that!`. Its naming follows the pattern of `verify_that!` since it uses the same idiom of returning a `googletest::Result`.
=> Introduce a function `verify_current_test_outcome`.

googletest/crate_docs.md, googletest/src/lib.rs, googletest/src/matchers/any_matcher.rs, googletest/src/matchers/mod.rs, googletest/tests/any_matcher_test.rs, googletest/tests/lib.rs
This macro creates a matcher which matches the value if at least one of its constituent matchers does. Having such a matcher is expected given the existence of `all!`.
=> Introduce a macro `any!` as a complement to the macro `all!`.

README.md, googletest/Cargo.toml, googletest/config.toml, googletest/src/matcher_support/summarize_diff.rs, googletest/src/matchers/display_matcher.rs, googletest/src/matchers/eq_deref_of_matcher.rs, googletest/src/matchers/eq_matcher.rs, googletest/src/matchers/str_matcher.rs, googletest/tests/colourised_diff_test.rs, googletest/tests/lib.rs, googletest/tests/no_color_test.rs
This makes use of the trait [`IsTerminal`](https://doc.rust-lang.org/stable/std/io/trait.IsTerminal.html), stabilised in Rust 1.70. If the Rust version is at least 1.70, then the library uses this trait to detect whether stdout is a terminal and only outputs colours by default if that is the case. When used on prior Rust versions, the library does not detect whether the output is a terminal and defaults to not outputing colours.
This also introduces support for two environment variables to override the default behaviour defined above:
* `NO_COLOR`, described in <http://no-color.org>.
* `FORCE_COLOR`, which is supported by a range of tools such as [Node.js](https://nodejs.org/api/cli.html#force_color1-2-3).
The environment variable `GTEST_RUST_NO_COLOR` is hereby no longer supported.
This …
=> Add support for using `is_terminal` and environment variables to determine whether to output ANSI colour sequences.

README.md, googletest/crate_docs.md, googletest_macro/src/lib.rs, integration_tests/src/integration_tests.rs
A test which only uses the `expect_*` family of assertions (thus requiring `#[googletest::test]`) will only ever return `Ok(())`. There is therefore no reason to require the function itself to return a `Result`. That requirement just creates unnecessary boilerplate.
This change modifies the `#[googletest::test]` implementation to remove the requirement that the return type be present. If it is present, then it must still be a `Result`.
The generated compiler error can no longer occur and is removed. It would be ideal to check whether the given return type is in fact a `Result` and return a compiler error if it is not, but that is beyond the scope of this change.
=> Support test functions returning () with `#[googletest::test]`.

googletest/src/lib.rs
The existing language stated that test functions *must* return `Result<()>`. This is not true in light of the `assert_*` family of macros and is no longer true when using `expect_*` in combination with `#[googletest::test]`. This change updates the docstring to indicate that a test function *may* return the type alias for fatal assertion failures and that some of the assertion macros evaluate to it.
=> Fix the language of the documentation of the type alias `Result`.

googletest/src/matchers/matches_pattern.rs, googletest/src/matchers/property_matcher.rs, googletest/tests/matches_pattern_test.rs, googletest/tests/property_matcher_test.rs
The keyword `ref` normally implies taking the object by reference and applied on non-reference identifier. However, in the `matchers_pattern` matcher, it was used to tag a method as returning references, with almost  a meaning of dereference.
For instance:
```
struct AStruct {
a_field: String
}
let a_struct = AStruct{a_field: "a_string".into()};
match a_struct {
AStruct { a_field: ref a_string } => println!("{a_string}")
}
```
can be understood as: "apply the pattern and take `a_struct.a_field` *by reference*".
Before this change:
```
#[derive(Debug)]
struct AStruct {
a_field: u32,
}
impl AStruct {
fn a_field(&self) -> &u32 {&self.a_field}
}
let actual = AStruct { a_field: 123 };
verify_that!(
actual,
matches_pattern!(AStruct {
ref a_field(): eq(123),
})
)
```
can be understood as: "apply …
=> Use star instead of ref in the property matchers (and also the matches_pattern matcher).

googletest/src/assertions.rs, integration_tests/src/integration_tests.rs
The library consequently supports trailing commas wherever comma-separated items are provided. The shorthand syntax for `elements_are!` and `unordered_elements_are!` did not support this. Thus the following would not compile:
```
verify_that!(vec![1, 2], [eq(1), eq(2),])
verify_that!(vec![1, 2], {eq(1), eq(2),})
```
This change adds support for trailing commas, making the developer experience more consistent within the library and with the Rust language in general.
=> Support trailing commas in the shorthand `element_are!` and `unordered_elements_are!` syntax.

integration_tests/Cargo.toml
Normally this is a transitive dependency of rstest with no direct dependency from integration-tests itself. But one of intermediate dependencies did not pin it, so it was silently upgraded to 1.5.4, which raised the MSRV from 1.59.0 to 1.61.0. Thus the integration tests could no longer run on our MSRV of 1.59.0.
This change pins the transitive dependency so that the integration tests compile again under our MSRV.
=> Pin the dependency on async-executor in the integration-tests crate to version 1.5.1.

.github/workflows/ci.yml, README.md, googletest/Cargo.toml, googletest_macro/Cargo.toml, integration_tests/Cargo.toml
This PR change the MSRV from 1.59 to 1.66.
The main dependent requiring 1.59 MSRV has updated their toolchain, so we are free to update in order to keep up with our dependencies.
This PR was generated with:
* Running `cargo upgrade` from [cargo-edit](https://crates.io/crates/cargo-edit)
* Running `cargo msrv` from [cargo-msrv](https://crates.io/crates/cargo-msrv)
* This resulted in 1.65
However, integrations tests failed at 1.65 probably due to a regression between 1.59 and 1.65 (probably between 1.62 and 1.63). This was probably fixed in [this PR](https://github.com/rust-lang/rust/commit/13f47f608e8e9fcdd60f64688e12f5f4c2f7c317) and all versions between 1.66 and 1.74 succeeded.
=> Update MSRV from 1.59 to 1.66

googletest/src/internal/test_outcome.rs, integration_tests/src/integration_tests.rs
Previously, subsequent non-fatal failure messages had no intervening whitespace, leading them to be visually hard to separate:
Value of: value
Expected: is equal to 3
Actual: 2,
which isn't equal to 3
at .*integration_tests/src/two_expect_that_failures.rs:[0-9]+:9
Value of: value
Expected: is equal to 4
Actual: 2,
which isn't equal to 4
at .*integration_tests/src/two_expect_that_failures.rs:[0-9]+:9
This modifies the `TestAssertionFailure::log` method to output an extra newline after a non-fatal failure message, making the individual failures easier to read:
Value of: value
Expected: is equal to 3
Actual: 2,
which isn't equal to 3
at .*integration_tests/src/two_expect_that_failures.rs:[0-9]+:9
Value of: value
Expected: is equal to 4
Actual: 2,
which isn't equal to 4
at …
=> Add an extra whitespace between subsequent non-fatal failure messages.

Cargo.toml
Previously, compiling the library on a recent Rust version gave a bunch of warnings:
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
This change eliminates those warnings by setting the resolver to version 2.
=> Set the resolver in the top-level Cargo.toml that of to the 2021 edition

googletest/src/assertions.rs, integration_tests/src/custom_error_message.rs, integration_tests/src/integration_tests.rs
This adds optional additional parameters to `assert_that!` and `expect_that!` which, if present, are formatted via `format!` into a failure message in the event of an assertion failure. The formatting takes place only if the assertion fails. Otherwise, the extra arguments have no effect.
Fixes #331
=> Support an extra failure message directly in `assert_that!` and `expect_that!`.

googletest/src/matchers/each_matcher.rs, googletest/tests/elements_are_matcher_test.rs, googletest/tests/matches_pattern_test.rs, integration_tests/Cargo.toml, integration_tests/src/integration_tests.rs
A recent change in Rust caused minor formatting changes when displaying fully qualified enum variants. Namely:
* The spaces around the `::` which were previously present were removed.
* The space between `vec!` and the vector content was removed. This breaks tests which assert descriptions, match explanations, and failure messages. These rely on the `Debug` representation of actual and expected values.
This fixes the tests so that they pass again in nightly while continuing to pass in the other versions. It removes text from the assertion where it is not crucial to what is being tested. In cases where it is crucial, the test now uses `contains_regex` with some operators so that the test passes whether or not the spaces are present.
=> Fix the tests on Rust nightly.

googletest/src/assertions.rs, integration_tests/src/integration_tests.rs
Previously, putting a trailing comma on `assert_that!` or `expect_that!` would produce a compilation error when no custom error message is present:
```
assert_that!(
value,
eq(2),  // Error!
);
```
This change adds support for trailing commas, making the behaviour of these macros more consistent with the rest of the library and Rust idioms.
Fixes #340
=> Add support for trailing commas on `assert_that!` and `expect_that!`.

googletest/src/matchers/contains_matcher.rs, googletest/src/matchers/eq_matcher.rs, googletest/src/matchers/some_matcher.rs, googletest/tests/tuple_matcher_test.rs, googletest/tests/unordered_elements_are_matcher_test.rs
This PR switch the `PartialEq` requirement in the `EqMatcher`. Instead of requiring `ExpectedT: PartialEq<ActualT>`, it will require `ActualT: PartialEq<ExpectedT>`. This change is normally not important as, most of the time, `ExpectedT == ActualT`, but it provides better ergonomy in the following case.
Libraries often need to implement a custom type representing the same data as a canonical type. For instance, `CustomI32` should be comparable with `i32`. The test could be written as:
```
#[test]
fn check() -> Result<()> {
let actual: CustomI32 = compute();
verify_that!(actual, eq(42))
}
```
But with the current definition, this require `i32: PartialEq<CustomI32>`, which cannot be implemented due to the orphan rule. However, with this change, implementing `CustomI32: PartialEq<i32>` is …
=> Flip the PartialEq constraint on EqMatcher

googletest_macro/src/lib.rs, integration_tests/Cargo.toml, integration_tests/src/integration_tests.rs, integration_tests/src/passing_test_with_should_panic.rs, run_integration_tests.sh
Previously, using `#[should_panic]` together with `#[googletest::test]` would result in compilation failure, since the latter always output a test function returning a `Result`, while `#[should_panic]` requires that the test function return `()`.
This modifies `#[googletest::test]` by detecting `#[should_panic]` and, when it is present, modifying the emitted function to not return anything.
When `#[should_panic]` is present, the test also panics if any non-fatal failure was recorded. The test is still allowed to run to completion. Otherwise, non-fatal assertion failures would be silently ignored, which is certainly not intended.
Fixes #328.
=> Add support for `#[should_panic]` to the `#[googletest::test]` macro.

googletest/src/description.rs, googletest/src/internal/description_renderer.rs, googletest/src/matchers/all_matcher.rs, googletest/src/matchers/conjunction_matcher.rs, googletest/src/matchers/mod.rs
This PR update:
* the matcher used in `all!` to rely on `ConjunctionMatcher` and not on `AllMatcher` (which is removed).
* `ConjunctionMatcher` to generate `Description` more similar to `AllMatcher`.
This PR will allow the usage of `all!` where a matcher is constrain with HRTB is expected. See #323 for more details.
=> Use `ConjunctionMatcher` in `all!` matcher.

googletest/src/description.rs, googletest/src/matchers/any_matcher.rs, googletest/src/matchers/conjunction_matcher.rs, googletest/src/matchers/disjunction_matcher.rs, googletest/src/matchers/mod.rs, googletest/tests/any_matcher_test.rs
This PR update:
* the matcher used in `any!` to rely on `DisjunctionMatcher` and not on `AnyMatcher` (which is removed).
*   `DisjunctionMatcher` to generate `Description` more similar to `AnyMatcher`.
* Remove the support of `any![]` (with empty matcher list). This should be implemented as `not(anything())` which is a surprising behavior.
* * This could not be done for `all!` since it is used in the `matches_pattern!` often with empty matcher list.
This PR will allow the usage of `any!` where a matcher is constrain with HRTB is expected. See https://github.com/google/googletest-rust/issues/323 for more details.
=> Use DisjunctionMatcher for any![] macro.

googletest/src/matcher_support/summarize_diff.rs
The warning was:
```
warning: variant name ends with the enum's name
--> googletest/src/matcher_support/summarize_diff.rs:232:5
|
232 |     CommonLineBuffer(Vec<&'a str>),
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#enum_variant_names
= note: `#[warn(clippy::enum_variant_names)]` on by default
```
=> Fix Clippy warning

googletest/src/matchers/field_matcher.rs, googletest/src/matchers/matches_pattern.rs, googletest/src/matchers/mod.rs, googletest/src/matchers/property_matcher.rs, googletest/tests/field_matcher_test.rs, googletest/tests/matches_pattern_test.rs, googletest/tests/property_matcher_test.rs
Support `Matcher<T>` and `Matcher<&T>` in the matcher `field!` `property!` and `matches_pattern!`. This simulates the [reference binding mode](https://doc.rust-lang.org/reference/patterns.html#binding-modes) of Rust pattern matching.
There may be some limitations regarding the usage of argument capture in `property!`, but this feature had problems and should be handled by the `predicate` matchers or a new matcher accepting both a mapping closure and a matcher on the value returned, similar to C++ `ResultOf`.
=> Support different binding mode in field!, property!, and matches_pattern!

googletest/src/matchers/matches_pattern.rs, googletest/src/matchers/mod.rs, googletest/src/matchers/predicate_matcher.rs, googletest/tests/composition_test.rs, googletest/tests/matches_pattern_test.rs
`matches_pattern!` was not working properly when matching against a reference pattern without field nor property as it was not general enough (the input type is chosen and stick a specific lifetime, when a general lifetime is possible). This can be the case with composite matchers requiring their inner matcher to accept reference with any lifetime.
Also update the `predicate` matcher to produce if possible matchers of any lifetime.
Fix #385
=> Fix pattern matching with reference pattern.

googletest/src/matcher_support/auto_ref_eq.rs, googletest/src/matcher_support/mod.rs, googletest/src/matchers/field_matcher.rs, googletest/src/matchers/matches_pattern.rs, googletest/src/matchers/property_matcher.rs, googletest/tests/field_matcher_test.rs, googletest/tests/matches_pattern_test.rs, googletest/tests/property_matcher_test.rs
This PR let the user remove `eq(...)` in `field!(...)`, `property!(...)` and `matches_pattern!(...)`.
Basically, `field!(MyStruct.my_field, eq(123))` is equivalent to `field!(MyStruct.my_field, 123)`. This is done through auto-ref specialization, as a macro is able to "inject" `eq(...)` if the second parameter of `field!(...)` is not a `MatcherBase`.
=> Add auto-ref eq in field! and property!.

googletest/Cargo.toml, googletest/src/matcher_support/summarize_diff.rs, googletest/src/matchers/display_matcher.rs, googletest/src/matchers/eq_matcher.rs, googletest/src/matchers/str_matcher.rs
This has three advantages:
* Avoid recomputing this configuration multiple times. Thread local variables are instantiated lazily, so it is only a positive.
* Remove dependency on `serial_test`
* Remove usage in unit tests of [`std::env::set_var`](https://doc.rust-lang.org/std/env/fn.set_var.html#safety) and [`std::env::remove_var`](https://doc.rust-lang.org/std/env/fn.remove_var.html#safety), which will eventually become unsafe [rust#27970](https://github.com/rust-lang/rust/issues/27970).
=> Save color configuration in a thread local variable

googletest/src/matcher_support/auto_eq.rs, googletest/src/matcher_support/mod.rs, googletest/src/matchers/field_matcher.rs, googletest/src/matchers/property_matcher.rs, googletest/tests/field_matcher_test.rs, googletest/tests/matches_pattern_test.rs, googletest/tests/property_matcher_test.rs
Autoref specialization was not working with `&Matcher` (which also implement `Matcher`). Inherent specialization seems to fix this issue.
=> Fix auto_eq to work with &Matcher.

googletest/src/assertions.rs, googletest/src/matcher_support/auto_eq.rs, googletest/src/matchers/all_matcher.rs, googletest/src/matchers/any_matcher.rs, googletest/src/matchers/elements_are_matcher.rs, googletest/src/matchers/field_matcher.rs, googletest/src/matchers/pointwise_matcher.rs, googletest/src/matchers/property_matcher.rs, googletest/src/matchers/unordered_elements_are_matcher.rs, googletest/tests/elements_are_matcher_test.rs, googletest/tests/unordered_elements_are_matcher_test.rs
Use in macro may lead to surprising behavior as the imported symbol may clash with symbols passed as macro parameters.
Hence, it is better to:
* Full qualify when possible (for struct, macro, etc...)
* Underscore import traits for extension traits
=> Remove symbol imports in macro.

.github/workflows/ci.yml, Cargo.lock, README.md, googletest/Cargo.toml, googletest/src/fixtures.rs, googletest/src/lib.rs, googletest_macro/Cargo.toml, googletest_macro/src/lib.rs, integration_tests/src/google_test_with_rstest.rs
This is the first PR for adding support of fixtures in googletest, only focused on putting the capabilities for synchronous tests.
This also bumps the msrv to 1.70.
=> Add fixtures support for sync test.

integration_tests/src/macro_hygiene.rs
Given the description of the commit that added macro_hygiene.rs, I believe that the name of the "ctor" module in this test should be "core", verifying that macros work properly when a crate under test has declared its own core module.
=> Rename the shadowing module from "ctor" to "core".

googletest_macro/src/lib.rs
`#[gtest]` will benefit from la10736/rstest#291, we could also benefit other test macros.
This is an attempt to improve capabilities among test macros to avoid duplicated test runs which is rare to be aware of.
The rationale is simple: procedure of attribute macro see only attributes following it. Macros next to processing macro will not see generated macro if it is generated in-place. So, instead of generating test macro in-place, appending generated test macro will let macros next to processing macro have chance to react, for example, not generate test macro if there is already one.
We could deprecate `#[googletest::test]` oneday after la10736/rstest#291 released.
See: tokio-rs/tokio#6497, d-e-s-o/test-log#46, frondeus/test-case#143, la10736/rstest#291, kezhuw/stuck#53.
Refs: …
=> Append generated test macro so next test macros are aware of it

googletest/crate_docs.md
Document new floating point matchers added on https://github.com/google/googletest-rust/pull/565.
=> Document `is_finite()` and `is_infinite()` matchers.

README.md
Add the OpenSSF badge to the readme. You can see the responses to the scorecard questionnaire on the [OpenSSF project page](https://www.bestpractices.dev/projects/10037), which is also linked from the badge.
=> Add the OpenSSF badge to README.md

googletest/src/assertions.rs
related #475
I went for using fully qualified method names, rather than `use $crate::GoogleTestSupport as _;` since it's more hygienic.
`use $crate::GoogleTestSupport as _;` can cause issues, resulting in a conflict, if the user introduces another method with the same name as one on `GoogleTestSupport`
=> Make `expect_that!` more hygienic

.github/dependabot.yml
This change removes Go and Docker package ecosystems from `dependabot.yml` since we don't use them.
=> Remove irrelevant package ecosystems from dependabot.yml

googletest/tests/reference_type_test.rs
This will help avoid any regression while attempting to fix #542.
=> Add a test for checking the regresion against reference types.

googletest/src/lib.rs, googletest_macro/src/lib.rs
This make `googletest::Result` similar to `std::result::Result` and can be used from one another. This plays nicer when `googletest::Result` is included through the `prelude` and the user would like to use something like `Result<(), MyError>`.
This is a similar trick used by anyhow.
=> Make Result parametric in the error type as well
